### PR TITLE
Fix the bastion lib to work with 2.4

### PR DESCRIPTION
**Pull request by mscherer**
Due to the change regarding inventory in 2.4, the code to extract
variable from inventory has changed a lot. However, since ansible 2.3
is now in RHEL, we have to keep compatibility with it for potentially
a long time.

So this code is a attempt at that, using a wrapper class to abstract
away the differences.

Once 2.3 is no longer supported (and no longer shipped), the code
will be cleaned again and fully ported to 2.4 only.

### CODE REVIEW

**Comment by mscherer** [comment]
So I have been using this code in prod since a few weeks, and now, RHEL 7 is using 2.4, so it might be the time to merge.

**Comment by duck-rh** [comment]
You just opened the PR so give me a few minutes to have a look :-).

**Comment by duck-rh** [comment]
I read the changes in the changelog but never read the actuals API details, so I can't check for errors but as you've been using it for a while…

As for the design it's quite elegant this way.

**Comment by mscherer** [comment]
I didn't read the details either, I just fixed because it broke 1 month ago (or more than 1 month, but I couldn't ignore anymore). And I think it is not bad, but I would still spend a few hours to clean the code in a few months.

**Pull request merged**
