### PR TITLE
Complete the doc on git-shell option

### PR DESCRIPTION
**Pull request by mscherer**
Also fix the conditional to be cleaner

### CODE REVIEW

**Comment by duck-rh** [comment]
This commit mixes non-doc changes, which are OK.

The doc should be clearer on the accepted values (boolean, "modes" with list of possible values…)

**Comment by duck-rh** [comment]
typo: trivailly

The rest is OK

**Comment by mscherer** [comment]
I fixed the typo

**Comment by duck-rh** [comment]
thanks

**Pull request merged**
