### PR TITLE
Various cleanups

### PR DESCRIPTION
**Pull request by mscherer**
That's a few clean up of the check_git_ignore.py file

### CODE REVIEW

**Comment by duck-rh** [comment]
seems OK, but a Python expert is needed to confirm, sorry

**Comment by mscherer** [comment]
I can ping @pilou- :)

**Comment by mscherer** [comment]
Also, please do not merge before the CVE is assigned.

**Comment by duck-rh** [comment]
any news from @pilou or the CVE?

**Comment by mscherer** [comment]
@pilou- so you got a CVE assigned ?

**Comment by pilou-** [comment]
No news. I forgot to accept MITRE CVE Terms of Use, but it's [done](https://github.com/distributedweaknessfiling/DWF-Legal-Acceptance/blob/master/Terms-Of-Use/pilou%40gmx.com). @kurtseifried did I forget something else ?

**Comment by duck-rh** [comment]
@pilou- can we merge? Could you have a look at the Python code (you're clearly much more experimented than I am)?

**Comment by pilou-** [comment]
Well, I am not the one requesting to not merge this PR :)

Anyway no news for the CVE.

**Comment by mscherer** [comment]
Ok so closing this one, as I think most of the code have been remerged somehow during various fixes.

**Pull request closed without merging**
