### PR TITLE
use Shippable instead of Travis

### PR DESCRIPTION
**Pull request by duck-rh**

### CODE REVIEW

**Comment by mscherer** [comment]
I would like to keep travis at least until we get a bit more feedback on shippable, so wait at least 1 or 2 months before switching. In the mean time, I am more in favor of merging https://github.com/OSAS/ansible-role-ansible_bastion/pull/31 (which we can't now that shippable was enabled on that repo...)

**Comment by mscherer** [comment]
For example, here we can see that shippable failed:

```
    "msg": "Error unpacking rpm package python2-crypto-2.6.1-9.el7.x86_64\n", 
```

And I rather have the features that I proposed 2 weeks ago to be merged now that I sent a working workaround.

**Comment by duck-rh** [comment]
I don't see the point in keeping something which is not working well. Also I need real-life difficult examples to work on, like this role. So we can reenable Travis and possibly just fail PR only if Travis fails. Nevertheless I'm clearly not in favour of keeping this unreliable tool.

**Comment by duck-rh** [comment]
This problem is not a shippable problem, as a platform, but in our image build rules. This is fixed now.

Also this PR fails because of a bug in the role itself, solved in #33 

And #33 fails because of the rpm/git installation problem, which could be worked-around by temporarily not testing the git installation. This is a limitation of our build system, not shippable.

**Comment by duck-rh** [comment]
So, it's already doing more than the Travis build and it seems better. I'd rather we work on making the improved buildsys we discuss happen NOW, than keeping something which does not really help fixing bugs.

**Comment by mscherer** [comment]
For now, I have PR that are waiting since 15 days on a merge. It took me 10 minutes to fix travis.yml, so I am gonna remove the shippable integration for now.

If you need a guinea pig, you can do that on your account, with a branch. Not on the main repository without asking first and breaking other people workflow. You can reopen/resubmit when the system will be working.

**Pull request closed without merging**
