### PR TITLE
Add hook to run a custom playbook when a new host is added

### PR DESCRIPTION
**Pull request by mscherer**
For now, this depend on the configuration file to be set, and
we need to write code to deploy the configuration file for the
bastion, which is not written yet, and I am not sure this
would go in the main role or not.

I would favor letting people do it with a simple template or
file rather than adding a set of options. A example configuration
file should also be added later along the documentation.

### CODE REVIEW

**Comment by duck-rh** [comment]
it's a good idea.

You don't know where the files are and how to process them so I agree it's better to let this be handled externally.

So I guess the doc needs much more information but the code is fine.

**Comment by mscherer** [comment]
For now, that's /etc/ansible_bastion.yml (option --config).

**Comment by mscherer** [comment]
I went ahead and added doc, and dropped for now the idea of a externally managed configuration file. We can refactor later once there is more clarity.

**Comment by duck-rh** [comment]
seems fine with the new limited scope

**Pull request merged**
