### PR TITLE
Add more logging of every run

### PR DESCRIPTION
**Pull request by mscherer**
So this permit to later debug who push and how did the script react.

### CODE REVIEW

**Comment by mscherer** [comment]
@duck-rh @pilou- could one of you take a look ( since both of you said "we need reviews" :p )

**Comment by duck-rh** [comment]
Seems nice. I'm not a Python expert so I leave it to @pilou- to check it.

Could we also add a message for steps like:
- update_requirements is true
- the result of the calculated playbooks_to_run
- the result of the calculated limits (for each playbooks_to_run)
  Not that the script needs to be debugged for calculation errors, I guess it works pretty well now, but to see which changes at which time impacted those hosts on this specific aspect.

**Comment by mscherer** [comment]
So update_requirements is True would appear in the list of command that were run (since if that's true, we add the command, and this is printed at the last part of the patch)

And so does the 2 others, since we will see the -l used, and the list of playbook applied..

I am not sure this bring more value.

However, I guess I could details a bit more the exact way to debug a run from a checkout (there is option for that, but that's a bit surprising to use all options).

**Comment by duck-rh** [comment]
Having the interesting result of what is about to be run in one line is easier than parsing many. Otherwise I agree. Maybe the list of playbooks is sufficient and the rest is enough with the commands logging.

**Comment by mscherer** [comment]
It all depend on the goal. This is mostly for auditing purpose, rather than debugging, as debugging would be done other way (in this case, take the argument and run with -n and the python debugguer to see what happened ).

**Comment by duck-rh** [comment]
You used "debug" so I got mislead, sorry.

**Pull request merged**
